# Generated by Django 4.2.30 on 2026-09-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20160627_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselocal',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.database', verbose_name='Database'),
        ),
        migrations.AlterField(
            model_name='databaselocal',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Portuguese'), ('es', 'Spanish')], max_length=10, verbose_name='language'),
        ),
    ]
