version: '3.4'

services:
    app:
        build:
            context: .
            target: prod
        container_name: fi-admin-api
        expose:
            - 8000
        volumes:
            - fiadmin_static_files:/app/static_files
        env_file:
            - ./.env.api
        command: gunicorn --workers 4 --bind 0.0.0.0:8000 fi-admin.wsgi --reload --timeout 1000
        restart: unless-stopped
        networks:
            - nginx-proxy
        deploy:
            resources:
                limits:
                    memory: ${MEMORY_APP_LIMIT}

    webserver:
        image: nginx:1.18-alpine
        container_name: fi-admin-api-webserver
        expose:
            - 80
        volumes:
            - ./etc/nginx:/etc/nginx/conf.d
            - fiadmin_static_files:/app/static_files
        depends_on:
            - app
        environment:
            - VIRTUAL_HOST=${VIRTUAL_HOST}
        networks:
            - nginx-proxy
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: ${MEMORY_WEBSERVER_LIMIT}

networks:
    nginx-proxy:
        external: true

volumes:
    fiadmin_static_files: