version: '3.4'

services:
  fi_admin:
    container_name: fi-admin
    restart: unless-stopped
    build:
      context: .
      target: prod
    image: ${IMAGE_TAG}
    expose:
      - 8000
    volumes:
      - ${LOG_PATH}:/logs
      - ${UPLOAD_PATH}:/app/uploads
      - ./bireme/fixtures/import/:/app/fixtures/import
      - static_files:/app/static_files
    env_file:
      - ./conf/app-env
    command: gunicorn --bind 0.0.0.0:8000 fi-admin.wsgi ${GUNICORN_PARAMS}
    networks:
      - nginx-proxy
    deploy:
      resources:
        limits:
          memory: ${MEMORY_APP_LIMIT}
        reservations:
          memory: ${MEMORY_APP_RESERVATION}

  www-static:
    container_name: fi-admin-www-static
    restart: unless-stopped
    image: nginx:1.18-alpine
    expose:
      - 80
    volumes:
      - ./conf/nginx/app:/etc/nginx/conf.d
      - static_files:/app/static_files
    depends_on:
      - fi_admin
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    networks:
      - nginx-proxy
    deploy:
      resources:
        limits:
          memory: ${MEMORY_WEBSERVER_LIMIT}
        reservations:
          memory: ${MEMORY_WEBSERVER_RESERVATION}

  www-docs:
    container_name: fi-admin-www-docs
    restart: unless-stopped
    image: nginx:1.18-alpine
    expose:
      - 80
    volumes:
      - ./conf/nginx/docs:/etc/nginx/conf.d
      - ${UPLOAD_PATH}:/app/uploads
    depends_on:
      - fi_admin
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_DOCS}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST_DOCS}
    networks:
      - nginx-proxy
    deploy:
      resources:
        limits:
          memory: ${MEMORY_WEBSERVER_LIMIT}
        reservations:
          memory: ${MEMORY_WEBSERVER_RESERVATION}

  cron:
    container_name: fi-admin-cron
    restart: unless-stopped
    image: ${IMAGE_TAG}
    volumes:
      - ${LOG_PATH}:/logs
    depends_on:
      - fi_admin
    env_file:
      - ./conf/app-env
    user: root
    command: crond -f -L /dev/stdout

  fi_admin_cache:
    image: bitnami/memcached:1.6.32
    container_name: fi-admin-cache
    restart: unless-stopped
    depends_on:
      - fi_admin
    ports:
      - 11211:11211
    environment:
      - MEMCACHED_CACHE_SIZE=128
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true

volumes:
  static_files:
