version: '3.4'

services:
  fi_admin_api:
    container_name: fi-admin-api
    restart: unless-stopped
    build:
      context: .
      target: prod
    image: ${IMAGE_TAG}
    expose:
      - 8000
    volumes:
      - ${LOG_PATH}:/logs
      - static_files:/app/static_files
    env_file:
      - ./conf/app-env-api
    command: gunicorn --bind 0.0.0.0:8000 fi-admin.wsgi ${GUNICORN_PARAMS}
    networks:
      - nginx-proxy
    deploy:
      resources:
        limits:
          memory: ${MEMORY_APP_LIMIT}
        reservations:
          memory: ${MEMORY_APP_RESERVATION}

  webserver:
    container_name: fi-admin-api-webserver
    restart: unless-stopped
    image: nginx:1.18-alpine
    expose:
      - 80
    volumes:
      - ./conf/nginx/api:/etc/nginx/conf.d
      - static_files:/app/static_files
    depends_on:
      - fi_admin_api
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    networks:
      - nginx-proxy
    deploy:
      resources:
        limits:
          memory: ${MEMORY_WEBSERVER_LIMIT}
        reservations:
          memory: ${MEMORY_WEBSERVER_RESERVATION}

networks:
  nginx-proxy:
    external: true

volumes:
  static_files:
