# Generated by Django 4.2.30 on 2026-09-15 14:11

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biblioref', '0028_auto_20220325_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='additional_physical_form_available_note',
            field=models.TextField(blank=True, verbose_name='Note of other available formats'),
        ),
        migrations.AlterField(
            model_name='referenceanalytic',
            name='clinical_trial_registry_name',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Clinical trial registry'),
        ),
        migrations.AlterField(
            model_name='referenceanalytic',
            name='pages',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Page identifier'),
        ),
    ]
