# Generated by Django 2.2.13 on 2020-11-26 13:58

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('leisref', '0012_auto_20180823_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='actrelationship',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='act',
            name='effectiveness_date',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, verbose_name='Effectiveness date'),
        ),
        migrations.AlterField(
            model_name='act',
            name='issue_date',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, validators=[utils.validators.valid_min_year], verbose_name='Issue date'),
        ),
        migrations.AlterField(
            model_name='act',
            name='publication_date',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, validators=[utils.validators.valid_min_year], verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='actcity',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='actcitylocal',
            name='act_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leisref.ActCity'),
        ),
        migrations.AlterField(
            model_name='actcitylocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='actcollection',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='actcollectionlocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='actcountryregion',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='actcountryregionlocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='actorganissuer',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='actorganissuerlocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='actrelationtype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='actrelationtypelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='actscope',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='actscopelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='actsource',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='actsourcelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='actstate',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='actstatelocal',
            name='act_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leisref.ActState'),
        ),
        migrations.AlterField(
            model_name='actstatelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='acttype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='acttypelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='acturl',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='databaselocal',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.CreateModel(
            name='ActAlternateID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_id', models.CharField(max_length=55, verbose_name='Alternate id')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leisref.Act', verbose_name='Act')),
            ],
            options={
                'verbose_name': 'Act Alternate ID',
                'verbose_name_plural': "Act Alternate ID's",
            },
        ),
    ]
