# Generated by Django 2.2.13 on 2021-02-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leisref', '0013_auto_20201126_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='issuer_organ',
            field=models.ManyToManyField(blank=True, to='leisref.ActOrganIssuer', verbose_name='Organ issuer'),
        ),
        migrations.AlterField(
            model_name='act',
            name='organ_issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_organ_issuer', to='leisref.ActOrganIssuer', verbose_name='Organ issuer'),
        ),
    ]
