# Generated by Django 2.2.13 on 2021-02-09 18:50

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist

def forward(apps, schema_editor):
    Act = apps.get_model("leisref", "Act")
    for act in Act.objects.all():
        if act.organ_issuer_id:
            try:
                act.issuer_organ.add(act.organ_issuer)
            except ObjectDoesNotExist:
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('leisref', '0014_auto_20210209_1847'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
