# Generated by Django 2.2.24 on 2025-09-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leisref', '0015_auto_20210209_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='english_translated_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='English translated title'),
        ),
        migrations.AlterField(
            model_name='acturl',
            name='language',
            field=models.CharField(blank=True, max_length=10, verbose_name='Language'),
        ),
    ]
