# Generated by Django 2.2.24 on 2026-01-26 20:07

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leisref', '0016_auto_20250930_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='official_ementa_translations',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Official ementa translations'),
        ),
        migrations.AddField(
            model_name='act',
            name='unofficial_ementa_translations',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Unofficial ementa translations'),
        ),
    ]
