# Generated by Django 4.2.30 on 2026-09-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0009_auto_20191030_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesiontermlocal',
            name='adhesionterm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.adhesionterm', verbose_name='Adhesion term'),
        ),
        migrations.AlterField(
            model_name='adhesiontermlocal',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='category',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='categorylocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prefix',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.')], max_length=45, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Closed')], default=-1, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='serviceproductlocal',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='serviceproductlocal',
            name='serviceproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.serviceproduct', verbose_name='Service/Product'),
        ),
        migrations.AlterField(
            model_name='type',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='typelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_type',
            field=models.CharField(choices=[('main', 'Main'), ('other', 'Other')], max_length=75, verbose_name='Type'),
        ),
    ]
