#!/bin/sh
DATE=$(date '+%Y-%m-%d')

cd /app

# reindex last month = 720 hours (30*24)

# index biblioref
uv run python manage.py update_index biblioref.ReferenceSource --nocommit --workers=10 --age 720 > /logs/update_index-monthly-${DATE}.log
uv run python manage.py update_index biblioref.ReferenceAnalytic --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# index events
uv run python manage.py update_index events --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# index lis
uv run python manage.py update_index main.Resource --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# index institution
uv run python manage.py update_index institution --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# index multimedia
uv run python manage.py update_index multimedia --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# index leisref
uv run python manage.py update_index leisref --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# index title
uv run python manage.py update_index title --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# commit changes
wget "${HAYSTACK_CONNECTION_URL}/update?commit=true" -O /logs/commit.log

# optimize index
wget "${HAYSTACK_CONNECTION_URL}/update?optimize=true" -O /logs/optimize.log