#!/bin/sh
DATE=$(date '+%Y-%m-%d')

cd /app

# reindex last month = 720 hours (30*24)

# index biblioref
python manage.py update_index biblioref.ReferenceSource --nocommit --workers=10 --age 720 > /logs/update_index-monthly-${DATE}.log
python manage.py update_index biblioref.ReferenceAnalytic --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# index events
python manage.py update_index events --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# index lis
python manage.py update_index main.Resource --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# index institution
python manage.py update_index institution --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# index multimedia
python manage.py update_index multimedia --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# index leisref
python manage.py update_index leisref --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

# index title
python manage.py update_index title --nocommit --workers=10 --age 720 >> /logs/update_index-monthly-${DATE}.log

