# Generated by Django 2.2.24 on 2026-01-22 17:20

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0003_auto_20250522_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description_translations',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Description translations'),
        ),
    ]
