# Generated by Django 4.2.30 on 2026-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_auto_20150910_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='language',
            field=models.CharField(max_length=10, verbose_name='Language'),
        ),
    ]
