# Generated by Django 2.2.24 on 2022-03-24 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import log.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('field', models.CharField(max_length=25, verbose_name='Field')),
                ('name', models.CharField(max_length=55, verbose_name='Name')),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Order')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('field_passive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='related.LinkedResourceType', verbose_name='Field passive')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource type',
                'verbose_name_plural': 'Resource types',
            },
        ),
        migrations.CreateModel(
            name='LinkedResourceTypeLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language')),
                ('name', models.CharField(max_length=55, verbose_name='name')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='related.LinkedResourceType', verbose_name='Resource type')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
            },
        ),
        migrations.CreateModel(
            name='LinkedResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('object_id', models.PositiveIntegerField()),
                ('internal_id', models.CharField(blank=True, max_length=55, verbose_name='FI-ADMIN Reference')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('link', models.URLField(blank=True, max_length=255, verbose_name='Link')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='related.LinkedResourceType', verbose_name='Type')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, log.models.AuditLog),
        ),
        migrations.CreateModel(
            name='LinkedResearchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('object_id', models.PositiveIntegerField()),
                ('link', models.URLField(max_length=255, verbose_name='Link')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, log.models.AuditLog),
        ),
    ]
