# Generated by Django 2.2.24 on 2022-03-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedresourcetype',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Order'),
        ),
    ]
