# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20150904_1546'),
        ('main', '0002_auto_20150831_1026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type', models.CharField(blank=True, max_length=55, verbose_name='Type', choices=[(b'510', 'Has edition in another language'), (b'520', 'It is edition in another language'), (b'530', 'Has subseries'), (b'540', 'It is subseries of'), (b'550', 'Has supplement or insertion'), (b'560', 'It is supplement or insertion'), (b'610', 'Continuation of'), (b'620', 'Partial continuation of'), (b'650', 'Absorbed'), (b'660', 'Absorbed in part'), (b'670', 'Formed by subdivision of'), (b'680', 'Fusion of...with...'), (b'710', 'Continued by'), (b'720', 'Continued in part by'), (b'750', 'Absorbed by'), (b'760', 'Absorbed in part by'), (b'770', 'Subdivided into'), (b'780', 'Merged with'), (b'790', 'To form')])),
                ('label', models.CharField(max_length=455, verbose_name='Title', blank=True)),
                ('issn', models.CharField(max_length=55, verbose_name='ISSN', blank=True)),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audit',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BVSSpecialty',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bvs', models.CharField(max_length=455, verbose_name='BVS', blank=True)),
                ('thematic_area', models.CharField(max_length=55, verbose_name='Thematic area', blank=True)),
            ],
            options={
                'verbose_name': 'BVS Specialty',
                'verbose_name_plural': 'BVS Specialties',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Fascic',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated', null=True)),
                ('record_type', models.CharField(max_length=55, verbose_name='Record type')),
                ('treatment_level', models.CharField(max_length=55, verbose_name='Title treatment level')),
                ('cooperative_center_code', models.CharField(max_length=55, verbose_name='Cooperative center')),
                ('title_id_number', models.CharField(max_length=55, verbose_name='Title ID')),
                ('notes', models.TextField(help_text='Enter one per line', verbose_name='Notes', blank=True)),
                ('year', models.CharField(max_length=255, verbose_name='Year')),
                ('volume', models.CharField(max_length=255, verbose_name='Volume', blank=True)),
                ('issue', models.CharField(max_length=55, verbose_name='Issue', blank=True)),
                ('status', models.CharField(max_length=55, verbose_name='Status (P/A)')),
                ('copies', models.CharField(max_length=55, verbose_name='Number of copies')),
                ('publication_type', models.CharField(max_length=55, verbose_name='Publication type')),
                ('classification', models.CharField(max_length=55, verbose_name='Classification')),
                ('creation_date', models.CharField(help_text=b'Format: YYYYMMDD', max_length=55, verbose_name='Creation date', blank=True)),
                ('last_change_date', models.CharField(help_text=b'Format: YYYYMMDD', max_length=55, verbose_name='Last change date', blank=True)),
                ('created_by', models.ForeignKey(related_name='+', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.PROTECT)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='IndexRange',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('index_code', models.CharField(blank=True, max_length=55, verbose_name='Index source code', choices=[(b'IM', 'Index Medicus'), (b'IL', 'Index Medicus Latin American'), (b'EM', 'Excerpta Medica'), (b'BA', 'Biological abstracts'), (b'LL', 'LILACS'), (b'SP', 'Public Health')])),
                ('initial_date', models.CharField(max_length=255, verbose_name='Initial date', blank=True)),
                ('initial_volume', models.CharField(max_length=55, verbose_name='Initial volume', blank=True)),
                ('initial_number', models.CharField(max_length=55, verbose_name='Initial number', blank=True)),
                ('final_date', models.CharField(max_length=255, verbose_name='Final date', blank=True)),
                ('final_volume', models.CharField(max_length=255, verbose_name='Final volume', blank=True)),
                ('final_number', models.CharField(max_length=255, verbose_name='Final number', blank=True)),
            ],
            options={
                'verbose_name': 'Index range',
                'verbose_name_plural': 'Index range',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated', null=True)),
                ('record_type', models.CharField(max_length=55, verbose_name='Record type')),
                ('treatment_level', models.CharField(max_length=55, verbose_name='Title treatment level')),
                ('cooperative_center_code', models.CharField(max_length=55, verbose_name='Cooperative center')),
                ('mask', models.CharField(max_length=55, verbose_name='Mask code')),
                ('status', models.CharField(max_length=55, verbose_name='Status')),
                ('volume', models.TextField(help_text='Enter one per line', verbose_name='Volume', blank=True)),
                ('issue', models.TextField(help_text='Enter one per line', verbose_name='Issue', blank=True)),
                ('volumes_sequence', models.CharField(max_length=55, verbose_name='Volumes sequence', blank=True)),
                ('issues_sequence', models.CharField(max_length=55, verbose_name='Issues sequence', blank=True)),
                ('notes', models.TextField(help_text='Enter one per line', verbose_name='Notes', blank=True)),
                ('filling_date', models.CharField(help_text=b'Format: YYYYMMDD', max_length=55, verbose_name='Filling date')),
                ('created_by', models.ForeignKey(related_name='+', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.PROTECT)),
                ('updated_by', models.ForeignKey(related_name='+', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.PROTECT)),
            ],
            options={
                'verbose_name': 'Mask',
                'verbose_name_plural': 'Masks',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OnlineResources',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('url', models.URLField(verbose_name='URL', blank=True)),
                ('issn_online', models.CharField(max_length=55, verbose_name='ISSN online', blank=True)),
                ('tco', models.BooleanField(default=False, verbose_name='ONLINE full text')),
                ('ndb', models.BooleanField(default=False, verbose_name='Unavailable for libraries')),
                ('pca', models.BooleanField(default=False, verbose_name='Allows buying articles')),
                ('access_type', models.CharField(blank=True, max_length=255, verbose_name='Access type', choices=[(b'ALIV', 'Free'), (b'ALAP', 'Free for subscribers'), (b'AAEL', 'Requires ONLINE subscription'), (b'ACOP', 'Requires ONLINE/PRINT subscription')])),
                ('access_control', models.CharField(blank=True, max_length=255, verbose_name='Access control', choices=[(b'LIVRE', 'Free'), (b'IP', 'IP'), (b'PASS', 'Password'), (b'IP/PASS', 'IP/Password')])),
                ('initial_period', models.CharField(max_length=455, verbose_name='Initial period', blank=True)),
                ('final_period', models.CharField(max_length=455, verbose_name='Final period', blank=True)),
                ('creation_date', models.CharField(help_text=b'Format: YYYYMMDD', max_length=55, verbose_name='Creation date', blank=True)),
                ('notes', models.TextField(help_text='Enter one per line', verbose_name='Observations', blank=True)),
            ],
            options={
                'verbose_name': 'Online resource',
                'verbose_name_plural': 'Online resources',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='OwnerList',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated', null=True)),
                ('owner', models.CharField(max_length=455, verbose_name='Owner', blank=True)),
                ('created_by', models.ForeignKey(related_name='+', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.PROTECT)),
                ('updated_by', models.ForeignKey(related_name='+', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.PROTECT)),
            ],
            options={
                'verbose_name': 'Owner List',
                'verbose_name_plural': 'Owners List',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated', null=True)),
                ('local_code', models.CharField(blank=True, max_length=55, verbose_name='Local code', choices=[(b'LOCAL', 'LOCAL')])),
                ('record_type', models.CharField(default=b'KS', max_length=55, verbose_name='Record type')),
                ('treatment_level', models.CharField(default=b'K', max_length=55, verbose_name='Title treatment level')),
                ('cooperative_center_code', models.CharField(max_length=55, verbose_name='Cooperative center')),
                ('national_code', models.CharField(max_length=55, verbose_name='National code')),
                ('id_number', models.CharField(max_length=55, verbose_name='ID number')),
                ('secs_number', models.CharField(max_length=55, verbose_name='SeCS number')),
                ('related_systems', models.TextField(help_text='Enter one per line', verbose_name='Related systems')),
                ('status', models.CharField(max_length=55, verbose_name='Publish status', choices=[(b'C', 'Current'), (b'?', 'Unknown'), (b'D', 'Suspended or closed')])),
                ('title', models.CharField(max_length=455, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=455, verbose_name='Subtitle', blank=True)),
                ('section', models.CharField(max_length=255, verbose_name='Section/Part')),
                ('section_title', models.CharField(max_length=455, verbose_name='Section/Part title')),
                ('responsibility_mention', models.TextField(help_text='Enter one per line', verbose_name='Responsibility Mention', blank=True)),
                ('shortened_title', models.CharField(max_length=455, verbose_name='Shortened title')),
                ('medline_shortened_title', models.CharField(max_length=455, verbose_name='MEDLINE shortened title', blank=True)),
                ('initial_date', models.CharField(max_length=255, verbose_name='Initial date', blank=True)),
                ('initial_volume', models.CharField(max_length=55, verbose_name='Initial volume', blank=True)),
                ('initial_number', models.CharField(max_length=55, verbose_name='Initial number', blank=True)),
                ('final_date', models.CharField(max_length=255, verbose_name='Final date', blank=True)),
                ('final_volume', models.CharField(max_length=255, verbose_name='Final volume', blank=True)),
                ('final_number', models.CharField(max_length=255, verbose_name='Final number', blank=True)),
                ('state', models.CharField(max_length=255, verbose_name='State', blank=True)),
                ('publication_level', models.CharField(blank=True, max_length=55, verbose_name='Publication level', choices=[(b'CT', 'Scientific/Technical'), (b'DI', 'Disclosure')])),
                ('title_alphabet', models.CharField(blank=True, max_length=55, verbose_name='Title alphabet', choices=[(b'A', 'Basic roman'), (b'B', 'Extended roman'), (b'C', 'Cyrillic'), (b'D', 'Japanese'), (b'E', 'Chinese'), (b'K', 'Korean'), (b'F', 'Arabic'), (b'G', 'Greek'), (b'H', 'Hebrew'), (b'I', 'Thai'), (b'J', 'Devanagari'), (b'L', 'Tamil'), (b'Z', 'Others')])),
                ('frequency', models.CharField(blank=True, max_length=55, verbose_name='Frequency', choices=[(b'A', 'Annual'), (b'B', 'Bimonthly (every two months)'), (b'C', 'Biweekly (twice per week)'), (b'D', 'Daily'), (b'E', 'Fortnightly (every two weeks)'), (b'F', 'Semiannual/Biannual'), (b'G', 'Biennial (every two years)'), (b'H', 'Triennial (every three years)'), (b'I', 'Three times a week'), (b'J', 'Three times a month'), (b'K', 'Irregular'), (b'M', 'Monthly'), (b'Q', 'Quarterly (four times a year)'), (b'S', 'Semimonthly (twice per month)'), (b'T', 'Triannual (three times a year)'), (b'W', 'Weekly'), (b'Z', 'Other frequencies'), (b'?', 'Unknown frequency')])),
                ('issn', models.CharField(max_length=255, verbose_name='ISSN')),
                ('coden', models.CharField(max_length=255, verbose_name='CODEN', blank=True)),
                ('medline_code', models.CharField(max_length=255, verbose_name='MEDLINE code', blank=True)),
                ('classification', models.TextField(help_text='Enter one per line', verbose_name='Classification', blank=True)),
                ('thematic_area', models.TextField(help_text='Enter one per line', verbose_name='Thematic area', blank=True)),
                ('user', models.TextField(help_text='Enter one per line', verbose_name='Users', blank=True)),
                ('acquisition_form', models.CharField(blank=True, max_length=55, verbose_name='Acquisition Form', choices=[(b'0', b'Unknown'), (b'1A', b'Purchase current'), (b'1B', b'Purchase canceled'), (b'2A', b'Exchange current'), (b'2B', b'Exchange canceled'), (b'3A', b'Donation current'), (b'3B', b'Donation canceled')])),
                ('acquisition_priority', models.CharField(blank=True, max_length=55, verbose_name='Acquisition priority', choices=[(b'1', 'Indispensable'), (b'2', 'Dispensable (exists in the country)'), (b'3', 'Dispensable (exists in the region)')])),
                ('comercial_editor', models.CharField(max_length=455, verbose_name='Comercial editor', blank=True)),
                ('city', models.CharField(max_length=455, verbose_name='City', blank=True)),
                ('lilacs_index_year', models.CharField(help_text=b'Format: YYYY', max_length=55, verbose_name='Index - Year/Start (LILACS)', blank=True)),
                ('notes', models.TextField(help_text='Enter one per line', verbose_name='Notes', blank=True)),
                ('bireme_notes', models.TextField(help_text='Enter one per line', verbose_name='BIREME notes', blank=True)),
                ('indexer_cc_code', models.CharField(max_length=55, verbose_name='Indexer center code', blank=True)),
                ('editor_cc_code', models.CharField(max_length=55, verbose_name='Editor code', blank=True)),
                ('creation_date', models.CharField(help_text=b'Format: YYYYMMDD', max_length=55, verbose_name='Creation date')),
                ('last_change_date', models.CharField(help_text=b'Format: YYYYMMDD', max_length=55, verbose_name='Last change date', blank=True)),
                ('abstract_language', models.ManyToManyField(related_name='abstract_language+', verbose_name='Abstract language', to='main.SourceLanguage', blank=True)),
                ('country', models.ManyToManyField(to='utils.Country', verbose_name='Country')),
                ('created_by', models.ForeignKey(related_name='+', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.PROTECT)),
                ('text_language', models.ManyToManyField(related_name='text_language+', verbose_name='Text language', to='main.SourceLanguage', blank=True)),
                ('updated_by', models.ForeignKey(related_name='+', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.PROTECT)),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TitleVariance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('type', models.CharField(blank=True, max_length=55, verbose_name='Type', choices=[(b'230', 'Parallel title'), (b'240', 'Other title forms')])),
                ('label', models.CharField(max_length=455, verbose_name='Title', blank=True)),
                ('issn', models.CharField(max_length=55, verbose_name='ISSN', blank=True)),
                ('initial_year', models.CharField(help_text=b'Format: YYYY', max_length=55, verbose_name='Initial year', blank=True)),
                ('title', models.ForeignKey(verbose_name='Original title', blank=True, to='title.Title', on_delete=models.PROTECT)),
            ],
            options={
                'verbose_name': 'Title variance',
                'verbose_name_plural': 'Title variances',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='onlineresources',
            name='owner',
            field=models.ForeignKey(verbose_name='Owner', blank=True, to='title.OwnerList', null=True, on_delete=models.PROTECT),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='onlineresources',
            name='title',
            field=models.ForeignKey(verbose_name='Title', blank=True, to='title.Title', null=True, on_delete=models.PROTECT),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='indexrange',
            name='title',
            field=models.ForeignKey(verbose_name='Title', blank=True, to='title.Title', on_delete=models.PROTECT),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='fascic',
            name='mask',
            field=models.ForeignKey(verbose_name='Mask code', to='title.Mask', on_delete=models.PROTECT),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='fascic',
            name='title',
            field=models.ForeignKey(verbose_name='Title', to='title.Title', on_delete=models.PROTECT),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='fascic',
            name='updated_by',
            field=models.ForeignKey(related_name='+', blank=True, editable=False, to=settings.AUTH_USER_MODEL, null=True, on_delete=models.PROTECT),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bvsspecialty',
            name='title',
            field=models.ForeignKey(verbose_name='Title', blank=True, to='title.Title', on_delete=models.PROTECT),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='audit',
            name='title',
            field=models.ForeignKey(verbose_name='Original title', blank=True, to='title.Title', on_delete=models.PROTECT),
            preserve_default=True,
        ),
    ]
