# Generated by Django 2.2.24 on 2025-02-04 19:20

from django.db import migrations, models
import django.db.models.deletion
import log.models
import title.models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0007_auto_20200214_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='type',
            field=models.CharField(blank=True, choices=[('510', 'Has edition in another language'), ('520', 'It is edition in another language'), ('530', 'Has subseries'), ('540', 'It is subseries of'), ('550', 'Has supplement or insertion'), ('560', 'It is supplement or insertion'), ('610', 'Continuation of'), ('620', 'Partial continuation of'), ('650', 'Absorbed'), ('660', 'Absorbed in part'), ('670', 'Formed by subdivision of'), ('680', 'Fusion of...with...'), ('710', 'Continued by'), ('720', 'Continued in part by'), ('750', 'Absorbed by'), ('760', 'Absorbed in part by'), ('770', 'Subdivided into'), ('780', 'Merged with'), ('790', 'To form')], max_length=55, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='indexrange',
            name='copy',
            field=models.CharField(blank=True, choices=[('MI', 'MEDLINE Index'), ('MR', 'MEDLINE Record')], max_length=55, verbose_name='Copy'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='creation_date',
            field=models.CharField(blank=True, help_text='Format: YYYYMMDD', max_length=55, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='last_change_date',
            field=models.CharField(blank=True, help_text='Format: YYYYMMDD', max_length=55, verbose_name='Last change date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='publication_type',
            field=models.CharField(blank=True, choices=[('S', 'Supplement'), ('NE', 'Special number')], max_length=55, verbose_name='Publication type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=55, verbose_name='Status (P/A)'),
        ),
        migrations.AlterField(
            model_name='mask',
            name='frequency',
            field=models.CharField(blank=True, choices=[('A', 'Annual'), ('B', 'Bimonthly (every two months)'), ('C', 'Biweekly (twice per week)'), ('D', 'Daily'), ('E', 'Fortnightly (every two weeks)'), ('F', 'Semiannual/Biannual'), ('G', 'Biennial (every two years)'), ('H', 'Triennial (every three years)'), ('I', 'Three times a week'), ('J', 'Three times a month'), ('K', 'Irregular'), ('M', 'Monthly'), ('Q', 'Quarterly (four times a year)'), ('S', 'Semimonthly (twice per month)'), ('T', 'Triannual (three times a year)'), ('U', 'Continuously updated'), ('W', 'Weekly'), ('Z', 'Other frequencies'), ('?', 'Unknown frequency')], max_length=55, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='onlineresources',
            name='access_control',
            field=models.CharField(blank=True, choices=[('LIVRE', 'Free'), ('IP', 'IP'), ('PASS', 'Password'), ('IP/PASS', 'IP/Password')], max_length=255, verbose_name='Access control'),
        ),
        migrations.AlterField(
            model_name='onlineresources',
            name='access_type',
            field=models.CharField(blank=True, choices=[('ALIV', 'Free'), ('ALAP', 'Free for subscribers'), ('AAEL', 'Requires ONLINE subscription'), ('ACOP', 'Requires ONLINE/PRINT subscription')], max_length=255, verbose_name='Access type'),
        ),
        migrations.AlterField(
            model_name='onlineresources',
            name='creation_date',
            field=models.CharField(blank=True, help_text='Format: YYYYMMDD', max_length=55, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='title',
            name='acquisition_form',
            field=models.CharField(blank=True, choices=[('0', 'Unknown'), ('1A', 'Purchase current'), ('1B', 'Purchase canceled'), ('2A', 'Exchange current'), ('2B', 'Exchange canceled'), ('3A', 'Donation current'), ('3B', 'Donation canceled')], max_length=55, verbose_name='Acquisition Form'),
        ),
        migrations.AlterField(
            model_name='title',
            name='acquisition_priority',
            field=models.CharField(blank=True, choices=[('1', 'Indispensable'), ('2', 'Dispensable (exists in the country)'), ('3', 'Dispensable (exists in the region)')], max_length=55, verbose_name='Acquisition priority'),
        ),
        migrations.AlterField(
            model_name='title',
            name='creation_date',
            field=models.CharField(help_text='Format: YYYYMMDD', max_length=55, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='title',
            name='frequency',
            field=models.CharField(blank=True, choices=[('A', 'Annual'), ('B', 'Bimonthly (every two months)'), ('C', 'Biweekly (twice per week)'), ('D', 'Daily'), ('E', 'Fortnightly (every two weeks)'), ('F', 'Semiannual/Biannual'), ('G', 'Biennial (every two years)'), ('H', 'Triennial (every three years)'), ('I', 'Three times a week'), ('J', 'Three times a month'), ('K', 'Irregular'), ('M', 'Monthly'), ('Q', 'Quarterly (four times a year)'), ('S', 'Semimonthly (twice per month)'), ('T', 'Triannual (three times a year)'), ('U', 'Continuously updated'), ('W', 'Weekly'), ('Z', 'Other frequencies'), ('?', 'Unknown frequency')], max_length=55, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='title',
            name='last_change_date',
            field=models.CharField(blank=True, help_text='Format: YYYYMMDD', max_length=55, verbose_name='Last change date'),
        ),
        migrations.AlterField(
            model_name='title',
            name='lilacs_index_year',
            field=models.CharField(blank=True, help_text='Format: YYYY', max_length=55, verbose_name='Index - Year/Start (LILACS)'),
        ),
        migrations.AlterField(
            model_name='title',
            name='local_code',
            field=models.CharField(blank=True, choices=[('LOCAL', 'LOCAL')], max_length=55, verbose_name='Local code'),
        ),
        migrations.AlterField(
            model_name='title',
            name='publication_level',
            field=models.CharField(blank=True, choices=[('CT', 'Scientific/Technical'), ('DI', 'Disclosure')], max_length=55, verbose_name='Publication level'),
        ),
        migrations.AlterField(
            model_name='title',
            name='record_type',
            field=models.CharField(default='KS', max_length=55, verbose_name='Record type'),
        ),
        migrations.AlterField(
            model_name='title',
            name='status',
            field=models.CharField(choices=[('C', 'Current'), ('?', 'Unknown'), ('D', 'Suspended or closed')], max_length=55, verbose_name='Publish status'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_alphabet',
            field=models.CharField(blank=True, choices=[('A', 'Basic roman'), ('B', 'Extended roman'), ('C', 'Cyrillic'), ('D', 'Japanese'), ('E', 'Chinese'), ('K', 'Korean'), ('F', 'Arabic'), ('G', 'Greek'), ('H', 'Hebrew'), ('I', 'Thai'), ('J', 'Devanagari'), ('L', 'Tamil'), ('Z', 'Others')], max_length=55, verbose_name='Title alphabet'),
        ),
        migrations.AlterField(
            model_name='title',
            name='treatment_level',
            field=models.CharField(default='K', max_length=55, verbose_name='Treatment level'),
        ),
        migrations.AlterField(
            model_name='titlevariance',
            name='type',
            field=models.CharField(blank=True, choices=[('230', 'Parallel title'), ('235', 'Shortened parallel title'), ('240', 'Other title forms')], max_length=55, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='PublicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image_file', models.FileField(blank=True, null=True, upload_to=title.models.image_upload, verbose_name='Select the logo image file')),
                ('logo_image_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Logo image url')),
                ('description', utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Description')),
                ('title', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='title.Title', verbose_name='Original title')),
            ],
            options={
                'verbose_name': 'Public information',
                'verbose_name_plural': 'Public informations',
            },
            bases=(models.Model, log.models.AuditLog),
        ),
    ]
