# Generated by Django 4.2.30 on 2026-09-15 14:11

from django.db import migrations, models
import title.models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0008_auto_20250204_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicinfo',
            name='logo_image_file',
            field=models.FileField(blank=True, null=True, upload_to=title.models.image_upload, verbose_name='Logo image file'),
        ),
        migrations.AlterField(
            model_name='title',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users+', to='title.users', verbose_name='Users'),
        ),
    ]
