# Generated by Django 4.2.30 on 2026-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related', '0002_auto_20220325_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedresearchdata',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dataset title'),
        ),
    ]
