# Generated by Django 2.2.24 on 2022-11-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0018_auto_20190805_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrycombinationlistdesc',
            name='language_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish Latin America'), ('pt-br', 'Portuguese'), ('es-es', 'Spanish Spain'), ('fr', 'French')], max_length=10, verbose_name='Language used for description'),
        ),
        migrations.AlterField(
            model_name='conceptlistdesc',
            name='language_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish Latin America'), ('pt-br', 'Portuguese'), ('es-es', 'Spanish Spain'), ('fr', 'French')], max_length=10, verbose_name='Language used for description'),
        ),
        migrations.AlterField(
            model_name='conceptlistqualif',
            name='language_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish Latin America'), ('pt-br', 'Portuguese'), ('es-es', 'Spanish Spain'), ('fr', 'French')], max_length=10, verbose_name='Language used for description'),
        ),
        migrations.AlterField(
            model_name='descriptiondesc',
            name='language_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish Latin America'), ('pt-br', 'Portuguese'), ('es-es', 'Spanish Spain'), ('fr', 'French')], max_length=10, verbose_name='Language used for description'),
        ),
        migrations.AlterField(
            model_name='descriptionqualif',
            name='language_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish Latin America'), ('pt-br', 'Portuguese'), ('es-es', 'Spanish Spain'), ('fr', 'French')], max_length=10, verbose_name='Language used for description'),
        ),
        migrations.AlterField(
            model_name='identifierconceptlistdesc',
            name='concept_relation_name',
            field=models.CharField(blank=True, choices=[('NRW', 'NRW - Narrower'), ('BRD', 'BRD - Broader'), ('REL', 'REL - Related but not broader or narrower')], max_length=3, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='identifierconceptlistdesc',
            name='preferred_concept',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Preferred concept'),
        ),
        migrations.AlterField(
            model_name='identifierconceptlistqualif',
            name='concept_relation_name',
            field=models.CharField(blank=True, choices=[('NRW', 'NRW - Narrower'), ('BRD', 'BRD - Broader'), ('REL', 'REL - Related but not broader or narrower')], max_length=3, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='identifierconceptlistqualif',
            name='preferred_concept',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Preferred concept'),
        ),
        migrations.AlterField(
            model_name='identifierdesc',
            name='abbreviation',
            field=models.ManyToManyField(blank=True, to='thesaurus.IdentifierQualif', verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='identifierdesc',
            name='date_created',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='identifierdesc',
            name='date_established',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, verbose_name='Date established'),
        ),
        migrations.AlterField(
            model_name='identifierdesc',
            name='date_revised',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, verbose_name='Date revised'),
        ),
        migrations.AlterField(
            model_name='identifierdesc',
            name='descriptor_class',
            field=models.CharField(blank=True, choices=[('1', '1 - Topical Descriptor'), ('2', '2 - Publication Types, for example Review'), ('3', '3 - Check Tag, e.g., Male - no tree number'), ('4', '4 - Geographic Descriptor')], max_length=2, verbose_name='Descriptor class'),
        ),
        migrations.AlterField(
            model_name='identifierqualif',
            name='date_created',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='identifierqualif',
            name='date_established',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, verbose_name='Date established'),
        ),
        migrations.AlterField(
            model_name='identifierqualif',
            name='date_revised',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, verbose_name='Date revised'),
        ),
        migrations.AlterField(
            model_name='pharmacologicalactionlist',
            name='language_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish Latin America'), ('pt-br', 'Portuguese'), ('es-es', 'Spanish Spain'), ('fr', 'French')], max_length=10, verbose_name='Language used for description'),
        ),
        migrations.AlterField(
            model_name='previousindexinglistdesc',
            name='language_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish Latin America'), ('pt-br', 'Portuguese'), ('es-es', 'Spanish Spain'), ('fr', 'French')], max_length=10, verbose_name='Language used for description'),
        ),
        migrations.AlterField(
            model_name='termlistdesc',
            name='concept_preferred_term',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Concept preferred term'),
        ),
        migrations.AlterField(
            model_name='termlistdesc',
            name='date_altered',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, verbose_name='Date altered'),
        ),
        migrations.AlterField(
            model_name='termlistdesc',
            name='date_created',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='termlistdesc',
            name='is_permuted_term',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Is permuted term'),
        ),
        migrations.AlterField(
            model_name='termlistdesc',
            name='language_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish Latin America'), ('pt-br', 'Portuguese'), ('es-es', 'Spanish Spain'), ('fr', 'French')], max_length=10, verbose_name='Language used for description'),
        ),
        migrations.AlterField(
            model_name='termlistdesc',
            name='lexical_tag',
            field=models.CharField(blank=True, choices=[('ABB', 'ABB - Abbreviation'), ('ABX', 'ABX - Embedded abbreviation'), ('ACR', 'ACR - Acronym'), ('ACX', 'ACX - Embedded acronym'), ('EPO', 'EPO - Eponym'), ('LAB', 'LAB - Lab number'), ('NAM', 'NAM - Proper name'), ('NON', 'NON - None'), ('TRD', 'TRD - Trade name')], max_length=3, verbose_name='Lexical categories'),
        ),
        migrations.AlterField(
            model_name='termlistdesc',
            name='record_preferred_term',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Record preferred term'),
        ),
        migrations.AlterField(
            model_name='termlistdesc',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Draft'), (1, 'Published'), (3, 'Deleted'), (5, 'Historical'), (10, 'Awaiting translation')], default=-1, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='termlistqualif',
            name='concept_preferred_term',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Concept preferred term'),
        ),
        migrations.AlterField(
            model_name='termlistqualif',
            name='date_altered',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, verbose_name='Date altered'),
        ),
        migrations.AlterField(
            model_name='termlistqualif',
            name='date_created',
            field=models.DateField(blank=True, help_text='DD/MM/YYYY', null=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='termlistqualif',
            name='is_permuted_term',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Is permuted term'),
        ),
        migrations.AlterField(
            model_name='termlistqualif',
            name='language_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish Latin America'), ('pt-br', 'Portuguese'), ('es-es', 'Spanish Spain'), ('fr', 'French')], max_length=10, verbose_name='Language used for description'),
        ),
        migrations.AlterField(
            model_name='termlistqualif',
            name='lexical_tag',
            field=models.CharField(blank=True, choices=[('ABB', 'ABB - Abbreviation'), ('ABX', 'ABX - Embedded abbreviation'), ('ACR', 'ACR - Acronym'), ('ACX', 'ACX - Embedded acronym'), ('EPO', 'EPO - Eponym'), ('LAB', 'LAB - Lab number'), ('NAM', 'NAM - Proper name'), ('NON', 'NON - None'), ('TRD', 'TRD - Trade name')], max_length=3, verbose_name='Lexical categories'),
        ),
        migrations.AlterField(
            model_name='termlistqualif',
            name='record_preferred_term',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Record preferred term'),
        ),
        migrations.AlterField(
            model_name='termlistqualif',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Draft'), (1, 'Published'), (3, 'Deleted'), (5, 'Historical'), (10, 'Awaiting translation')], default=-1, null=True, verbose_name='Status'),
        ),
    ]
