# Generated by Django 4.2.30 on 2026-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0019_auto_20221108_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycombinationlistdesc',
            name='language_code',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish Latin America'), ('pt-br', 'Portuguese'), ('es-es', 'Spanish Spain'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
    ]
