# Generated by Django 2.2.24 on 2022-03-25 12:06

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220325_1131'),
        ('biblioref', '0027_referencesource_doi_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencesource',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.License', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='abstract',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='author_keyword',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Author keyword'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='descriptive_information',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Descriptive information'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='electronic_address',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Electronic address'),
        ),
        migrations.AlterField(
            model_name='referenceanalytic',
            name='clinical_trial_registry_name',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Clinical trial registry name'),
        ),
        migrations.AlterField(
            model_name='referenceanalytic',
            name='corporate_author',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Corporate author'),
        ),
        migrations.AlterField(
            model_name='referenceanalytic',
            name='individual_author',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Individual author'),
        ),
        migrations.AlterField(
            model_name='referenceanalytic',
            name='pages',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Pages'),
        ),
        migrations.AlterField(
            model_name='referenceanalytic',
            name='reference_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioref.Reference'),
        ),
        migrations.AlterField(
            model_name='referenceanalytic',
            name='thesis_dissertation_analytic_leader',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='referenceanalytic',
            name='title',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, help_text='Field mandatory', null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='referencelocal',
            name='call_number',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Call number'),
        ),
        migrations.AlterField(
            model_name='referencesource',
            name='corporate_author_collection',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Corporate author'),
        ),
        migrations.AlterField(
            model_name='referencesource',
            name='corporate_author_monographic',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Corporate author'),
        ),
        migrations.AlterField(
            model_name='referencesource',
            name='individual_author_collection',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Individual author'),
        ),
        migrations.AlterField(
            model_name='referencesource',
            name='individual_author_monographic',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Individual author'),
        ),
        migrations.AlterField(
            model_name='referencesource',
            name='reference_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioref.Reference'),
        ),
        migrations.AlterField(
            model_name='referencesource',
            name='thesis_dissertation_leader',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='referencesource',
            name='title_collection',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='referencesource',
            name='title_monographic',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Title'),
        ),
    ]
