# Generated by Django 2.2.28 on 2022-06-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
    ]
