#!/bin/sh
DATE=$(date '+%Y-%m-%d')

cd /app

# reindex last week = 168 hours (7*24)

# index biblioref
uv run python manage.py update_index biblioref.ReferenceSource --nocommit --workers=5 --age 168 > /logs/update_index-weekly-${DATE}.log
uv run python manage.py update_index biblioref.ReferenceAnalytic --nocommit --workers=5 --age 168 >> /logs/update_index-weekly-${DATE}.log

# index events
uv run python manage.py update_index events --nocommit --workers=5 --age 168 >> /logs/update_index-weekly-${DATE}.log

# index lis
uv run python manage.py update_index main.Resource --nocommit --workers=5 --age 168 >> /logs/update_index-weekly-${DATE}.log

# index institution
uv run python manage.py update_index institution --nocommit --workers=5 --age 168 >> /logs/update_index-weekly-${DATE}.log

# index multimedia
uv run python manage.py update_index multimedia --nocommit --workers=5 --age 168 >> /logs/update_index-weekly-${DATE}.log

# index leisref
uv run python manage.py update_index leisref --nocommit --workers=5 --age 168 >> /logs/update_index-weekly-${DATE}.log

# index title
uv run python manage.py update_index title --nocommit --workers=5 --age 168 >> /logs/update_index-weekly-${DATE}.log

# commit changes
wget "${HAYSTACK_CONNECTION_URL}/update?commit=true" -O /logs/commit.log