#!/bin/sh
DATE=$(date '+%Y-%m-%d')

cd /app

# reindex last day = 24 hours

# index biblioref
python manage.py update_index biblioref.ReferenceSource --age 24 > /logs/update_index-daily-${DATE}.log
python manage.py update_index biblioref.ReferenceAnalytic --age 24 >> /logs/update_index-daily-${DATE}.log

# index events
python manage.py update_index events --age 24 >> /logs/update_index-daily-${DATE}.log

# index lis
python manage.py update_index main.Resource --age 24 >> /logs/update_index-daily-${DATE}.log

# index institution
python manage.py update_index institution --age 24 >> /logs/update_index-daily-${DATE}.log

# index multimedia
python manage.py update_index multimedia --age 24 >> /logs/update_index-daily-${DATE}.log

# index leisref
python manage.py update_index leisref --age 24 >> /logs/update_index-daily-${DATE}.log