#!/bin/sh
DATE=$(date '+%Y-%m-%d')

cd /app

# reindex last day = 24 hours

# index biblioref
uv run python manage.py update_index biblioref.ReferenceSource --nocommit --age 24 > /logs/update_index-daily-${DATE}.log
uv run python manage.py update_index biblioref.ReferenceAnalytic --nocommit --age 24 >> /logs/update_index-daily-${DATE}.log

# index events
uv run python manage.py update_index events --nocommit --age 24 >> /logs/update_index-daily-${DATE}.log

# index lis
uv run python manage.py update_index main.Resource --nocommit --age 24 >> /logs/update_index-daily-${DATE}.log

# index institution
uv run python manage.py update_index institution --nocommit --age 24 >> /logs/update_index-daily-${DATE}.log

# index multimedia
uv run python manage.py update_index multimedia --nocommit --age 24 >> /logs/update_index-daily-${DATE}.log

# index leisref
uv run python manage.py update_index leisref --nocommit --age 24 >> /logs/update_index-daily-${DATE}.log

# index title
uv run python manage.py update_index title --nocommit --age 24 >> /logs/update_index-daily-${DATE}.log

# commit changes
wget "${HAYSTACK_CONNECTION_URL}/update?commit=true" -O /logs/commit.log