# Generated by Django 2.2.28 on 2022-06-28 12:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Title')),
                ('slot', models.CharField(choices=[('dashboard', 'Dashboard')], max_length=30, verbose_name='Slot')),
                ('order', models.SmallIntegerField(blank=True, null=True, verbose_name='Order')),
                ('user_profile', models.CharField(blank=True, choices=[('edi', 'Editor'), ('doc', 'Documentalist'), ('editor_llxp', 'Editor LILACS-Express')], max_length=30, verbose_name='User profile')),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Text block',
                'verbose_name_plural': 'Text blocks',
            },
        ),
        migrations.CreateModel(
            name='TextBlockLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language')),
                ('title', models.CharField(max_length=155, verbose_name='Title')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('text_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_block.TextBlock', verbose_name='Text block')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
            },
        ),
    ]
