# Generated by Django 2.2.24 on 2025-05-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_auto_20180220_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxcode',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='auxcodelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='countrylocal',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
    ]
