# Generated by Django 2.2.24 on 2023-06-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestevent',
            name='origin',
            field=models.URLField(blank=True, verbose_name='Origin'),
        ),
    ]
