# Generated by Django 4.2.30 on 2026-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20160203_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='help',
            name='source',
            field=models.CharField(choices=[('resources', 'Resources'), ('events', 'Events'), ('multimedia', 'Multimedia'), ('biblioref', 'Bibliographic Reference'), ('leisref', 'Act reference'), ('oer', 'Educational resources')], max_length=25, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='helplocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
    ]
