# Generated by Django 2.2.24 on 2025-10-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220325_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='ai_model',
            field=models.CharField(blank=True, max_length=50, verbose_name='AI Model'),
        ),
        migrations.AddField(
            model_name='descriptor',
            name='ai_suggestion',
            field=models.BooleanField(default=False, verbose_name='AI Suggestion?'),
        ),
        migrations.AlterField(
            model_name='descriptor',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Admitted'), (2, 'Refused')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Admitted'), (2, 'Refused')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='resourcethematic',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Admitted'), (2, 'Refused')], default=1, verbose_name='Status'),
        ),
    ]
