# Generated by Django 4.2.30 on 2026-09-15 14:11

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oer', '0004_auto_20170623_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='audiencelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='coursetypelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='difficultylocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='format',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='formatlocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='interactivitylevel',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='interactivitylevellocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='interactivitytype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='interactivitytypelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='learningcontext',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='learningcontextlocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='learningresourcetype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='learningresourcetypelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='license',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='licenselocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='oer',
            name='CVSP_resource',
            field=models.BooleanField(default=True, verbose_name='CVSP resource'),
        ),
        migrations.AlterField(
            model_name='oer',
            name='aggregation_level',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=55, verbose_name='Aggregation Level'),
        ),
        migrations.AlterField(
            model_name='oer',
            name='contributor',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Contributor'),
        ),
        migrations.AlterField(
            model_name='oer',
            name='creator',
            field=utils.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': None}, null=True, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='oerurl',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='relationtypelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='structurelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='tecresourcetype',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='tecresourcetypelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='type',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='typelocal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('fr', 'French')], max_length=10, verbose_name='language'),
        ),
    ]
